import { IPC } from '../../electron/ipc/channels';
import { store } from './core';
import { initTaskInStore } from './tasks';
import { saveState } from './persistence';
import { warn as logWarn } from '../lib/log';
import type { MobileTaskSpawnedPayload } from '../ipc/types';
import type { Agent, Task } from './types';

function findProjectIdByRoot(projectRoot: string): string | undefined {
  return store.projects.find((p) => p.path === projectRoot)?.id;
}

function findAgentDefById(id: string) {
  return store.availableAgents.find((a) => a.id === id);
}

function isValidPayload(data: unknown): data is MobileTaskSpawnedPayload {
  if (!data || typeof data !== 'object') return false;
  const d = data as Record<string, unknown>;
  return (
    typeof d.taskId === 'string' &&
    typeof d.agentId === 'string' &&
    typeof d.projectRoot === 'string' &&
    typeof d.agentDefId === 'string' &&
    typeof d.taskName === 'string' &&
    (d.baseBranch === null || typeof d.baseBranch === 'string') &&
    typeof d.branchName === 'string' &&
    typeof d.worktreePath === 'string' &&
    typeof d.prompt === 'string'
  );
}

function handleMobileTaskSpawned(data: unknown): void {
  try {
    if (!isValidPayload(data)) {
      logWarn('mobileTaskSync', 'dropped invalid payload', { data });
      return;
    }
    // Defensive: if the task already exists in store (e.g. duplicate IPC),
    // skip — initTaskInStore would otherwise overwrite local edits.
    if (store.tasks[data.taskId]) return;

    const projectId = findProjectIdByRoot(data.projectRoot);
    if (!projectId) {
      logWarn('mobileTaskSync', 'no matching project for projectRoot', {
        projectRoot: data.projectRoot,
      });
      return;
    }

    const agentDef = findAgentDefById(data.agentDefId);
    if (!agentDef) {
      logWarn('mobileTaskSync', 'unknown agent preset', { agentDefId: data.agentDefId });
      return;
    }

    const task: Task = {
      id: data.taskId,
      name: data.taskName,
      nameIsAutoGenerated: false,
      projectId,
      gitIsolation: 'worktree',
      baseBranch: data.baseBranch ?? undefined,
      branchName: data.branchName,
      worktreePath: data.worktreePath,
      agentIds: [data.agentId],
      selectedAgentId: data.agentId,
      shellAgentIds: [],
      notes: '',
      lastPrompt: '',
      // Prompt is already sent by main; only keep it as savedInitialPrompt
      // so the task header can display it. Do NOT set initialPrompt — that
      // would make the renderer auto-send it again.
      savedInitialPrompt: data.prompt,
      promptedAgentIds: [data.agentId],
    };

    const agent: Agent = {
      id: data.agentId,
      taskId: data.taskId,
      def: agentDef,
      resumed: false,
      status: 'running',
      exitCode: null,
      signal: null,
      lastOutput: [],
      generation: 0,
      // PTY is already running in main; the TerminalView will reattach
      // (instead of spawning a second process) when it mounts.
      attachExisting: true,
    };

    initTaskInStore(data.taskId, task, agent, projectId, agentDef);
    void saveState();
  } catch (err) {
    // A throw in here would otherwise propagate up through Electron's IPC
    // dispatcher and leave the subscription in a half-broken state. Logging
    // and swallowing keeps the rest of the renderer responsive.
    logWarn('mobileTaskSync', 'handler threw', {
      err: err instanceof Error ? err.message : String(err),
    });
  }
}

/** Listen for mobile-spawned tasks pushed from the main process and mirror
 *  them into the renderer's store. Returns a cleanup function.
 *
 *  The subscribe call is wrapped in try/catch: preload.cjs ALLOWED_CHANNELS
 *  is read once at Electron startup, so if a developer adds this channel but
 *  only hot-reloads the renderer (without restarting Electron), the older
 *  preload throws "Blocked IPC channel" synchronously. We want the rest of
 *  the renderer's onMount work to keep running in that case, not unwind. */
export function startMobileTaskSyncSubscription(): () => void {
  try {
    return window.electron.ipcRenderer.on(IPC.MobileTaskSpawned, handleMobileTaskSpawned);
  } catch (err) {
    logWarn('mobileTaskSync', 'subscribe failed — restart Electron after preload changes', {
      err: err instanceof Error ? err.message : String(err),
    });
    return () => {};
  }
}
