// Barrel file — re-exports from domain modules
export { store } from './core';
export {
  getProject,
  addProject,
  removeProject,
  removeProjectWithTasks,
  updateProject,
  getProjectPath,
  getProjectBranchPrefix,
  pickAndAddProject,
  validateProjectPaths,
  relinkProject,
  isProjectMissing,
  projectIsGitRepo,
  PASTEL_HUES,
} from './projects';
export {
  loadAgents,
  addAgentToTask,
  closeAgentInTask,
  markAgentExited,
  restartAgent,
  switchAgent,
  addCustomAgent,
  removeCustomAgent,
  updateCustomAgent,
} from './agents';
export {
  createTask,
  createImportedTask,
  closeTask,
  retryCloseTask,
  mergeTask,
  pushTask,
  updateTaskName,
  updateTaskBranch,
  updateTaskNotes,
  sendPrompt,
  setLastPrompt,
  clearInitialPrompt,
  clearPrefillPrompt,
  setPrefillPrompt,
  reorderTask,
  spawnShellForTask,
  runBookmarkInTask,
  closeShell,
  hasDirectTask,
  collapseTask,
  uncollapseTask,
  getGitHubDropDefaults,
  setNewTaskDropUrl,
  setNewTaskPrefillPrompt,
  setPlanContent,
  setStepsContent,
  setTaskStepsEnabled,
  setTaskLastInputAt,
} from './tasks';
export {
  setActiveTask,
  setActiveAgent,
  navigateAgent,
  moveActiveTask,
  jumpToTask,
  toggleNewTaskDialog,
} from './navigation';
export {
  registerFocusFn,
  unregisterFocusFn,
  triggerFocus,
  registerAction,
  unregisterAction,
  triggerAction,
  getTaskFocusedPanel,
  setTaskFocusedPanel,
  isPanelFocused,
  isPanelFocusedPrefix,
  focusSidebar,
  unfocusSidebar,
  unfocusPlaceholder,
  navigateRow,
  navigateColumn,
  navigateTask,
  setPendingAction,
  clearPendingAction,
  toggleHelpDialog,
  toggleSettingsDialog,
  sendActivePrompt,
  setSidebarFocusedProjectId,
} from './focus';
export type { PanelId, PendingAction, TaskViewportVisibility } from './types';
export { saveState, loadState } from './persistence';
export {
  getGlobalScale,
  adjustGlobalScale,
  resetGlobalScale,
  getPanelUserSize,
  setPanelUserSize,
  deletePanelUserSize,
  getTaskViewportVisibility,
  setTaskViewportVisibility,
  toggleSidebar,
  toggleArena,
  toggleFocusMode,
  toggleTaskFocusMode,
  setTaskSplitMode,
  setTerminalFont,
  setThemePreset,
  applyAppearanceMode,
  setAppearanceMode,
  setLightTheme,
  setDarkTheme,
  setAutoTrustFolders,
  setShowPlans,
  setShowPromptInput,
  setShowSidebarTips,
  setShowSidebarProgress,
  setFontSmoothing,
  setDesktopNotificationsEnabled,
  setVerboseLogging,
  setInactiveColumnOpacity,
  setEditorCommand,
  setDockerImage,
  setDockerAvailable,
  setShareDockerAgentAuth,
  setAskCodeProvider,
  setMinimaxApiKey,
  setWindowState,
} from './ui';
export {
  getTaskDotStatus,
  getTaskAttentionState,
  taskNeedsAttention,
  markAgentOutput,
  clearAgentActivity,
  getAgentOutputTail,
  stripAnsi,
  onAgentReady,
  offAgentReady,
  normalizeForComparison,
  normalizeCurrentFrame,
  looksLikeQuestion,
  isTrustQuestionAutoHandled,
  isAutoTrustSettling,
  isAgentAskingQuestion,
  refreshTaskStatus,
  startTaskStatusPolling,
  stopTaskStatusPolling,
  rescheduleTaskStatusPolling,
} from './taskStatus';
export type { TaskAttentionState, TaskDotStatus } from './taskStatus';
export { showNotification, clearNotification } from './notification';
export { startPrChecksSubscription, getPrChecks, type PrChecksState } from './pr-checks';
export {
  startConflictPreflightSubscription,
  getConflictPreflight,
  type ConflictPreflightState,
} from './conflict-preflight';
export { getCompletedTasksTodayCount, getMergedLineTotals } from './completion';
export {
  createTerminal,
  closeTerminal,
  updateTerminalName,
  syncTerminalCounter,
} from './terminals';
export { startRemoteAccess, stopRemoteAccess, refreshRemoteStatus } from './remote';
export {
  resolvedBindings,
  allBindings,
  loadKeybindings,
  selectPreset,
  setUserOverride,
  clearUserOverride,
  resetAllBindings,
  checkConflict,
  dismissMigrationBanner,
} from './keybindings';
