import type { AgentDef, StepEntry, WorktreeStatus } from '../ipc/types';
import type { DockerSource } from '../lib/docker';
import type { LookPreset, AppearanceMode } from '../lib/look';
import type { KeyBinding } from '../lib/keybindings';
import type { CustomTheme } from '../lib/custom-theme';

/** A user override for a binding: partial key/modifiers to apply, or null to unbind. */
export type KeybindingOverride = Partial<Pick<KeyBinding, 'key' | 'modifiers'>> | null;

export type GitIsolationMode = 'worktree' | 'direct' | 'none';

export interface StagedNotification {
  batchId: string;
  notificationIds: string[];
  text: string;
  autoFireAt: number;
  userEdited: boolean;
  hiddenCompletionCount?: number;
}

export interface TaskGitStatusSnapshot extends WorktreeStatus {
  refreshedAt: number;
  error?: string;
  refreshing?: boolean;
  stale?: boolean;
}

export type TaskViewportVisibility = 'visible' | 'offscreen-left' | 'offscreen-right';

export interface TerminalBookmark {
  id: string;
  command: string;
}

export interface Project {
  id: string;
  name: string;
  path: string;
  color: string;
  branchPrefix?: string; // default "task" if unset
  deleteBranchOnClose?: boolean; // default true if unset
  defaultGitIsolation?: GitIsolationMode;
  defaultBaseBranch?: string;
  /** Coverage artifact path relative to the repo root. */
  coverageReportPath?: string;
  terminalBookmarks?: TerminalBookmark[];
  isGitRepo?: boolean; // undefined treated as true for backward compat
  /** Per-project opt-in for Telegram control. Default false. The bot refuses
   *  to attach to a project whose flag is false. */
  telegramOptIn?: boolean;
  /** When true, sustained Telegram tail backpressure pauses the agent's PTY.
   *  Default false. Only meaningful when `telegramOptIn === true`. */
  telegramPauseOnBackpressure?: boolean;
}

export interface Agent {
  id: string;
  taskId: string;
  def: AgentDef;
  resumed: boolean;
  status: 'running' | 'exited';
  exitCode: number | null;
  signal: string | null;
  lastOutput: string[];
  generation: number;
  spawnDelayMs?: number;
  attachExisting?: boolean;
}

export interface Task {
  id: string;
  name: string;
  nameIsAutoGenerated?: boolean;
  projectId: string;
  branchName: string;
  worktreePath: string;
  agentIds: string[];
  selectedAgentId?: string;
  shellAgentIds: string[];
  notes: string;
  lastPrompt: string;
  promptedAgentIds?: string[];
  initialPrompt?: string; // auto-sends when agent is ready
  savedInitialPrompt?: string;
  prefillPrompt?: string; // fills prompt input without sending
  closingStatus?: 'closing' | 'removing' | 'error';
  closingError?: string;
  gitIsolation: GitIsolationMode;
  baseBranch?: string;
  externalWorktree?: boolean;
  skipPermissions?: boolean;
  dockerMode?: boolean;
  dockerSource?: DockerSource;
  dockerImage?: string;
  githubUrl?: string;
  collapsed?: boolean;
  savedAgentDef?: AgentDef;
  savedAgentDefs?: AgentDef[];
  savedSelectedAgentIndex?: number;
  savedPromptedAgentIndexes?: number[];
  planContent?: string;
  planFileName?: string;
  stepsEnabled?: boolean;
  stepsContent?: StepEntry[];
  lastInputAt?: string;
  stagedNotification?: StagedNotification;
  // Coordinator fields
  coordinatorMode?: boolean;
  propagateSkipPermissions?: boolean;
  coordinatedBy?: string;
  controlledBy?: 'coordinator' | 'human';
  mcpConfigPath?: string;
  mcpLaunchArgs?: string[];
  preambleFileExistedBefore?: boolean;
  signalDoneReceived?: boolean;
  signalDoneAt?: string;
  signalDoneConsumed?: boolean;
  needsReview?: boolean;
  mcpStartupStatus?: 'pending' | 'ready' | 'error';
  mcpStartupError?: string;
}

export interface Terminal {
  id: string;
  name: string;
  agentId: string;
  closingStatus?: 'closing' | 'removing';
}

export interface PersistedTask {
  id: string;
  name: string;
  nameIsAutoGenerated?: boolean;
  projectId: string;
  branchName: string;
  worktreePath: string;
  notes: string;
  lastPrompt: string;
  promptedAgentIds?: string[];
  initialPrompt?: string;
  shellCount: number;
  agentDef: AgentDef | null;
  agentDefs?: AgentDef[];
  agentIds?: string[];
  selectedAgentId?: string;
  gitIsolation: GitIsolationMode;
  baseBranch?: string;
  externalWorktree?: boolean;
  skipPermissions?: boolean;
  dockerMode?: boolean;
  dockerSource?: DockerSource;
  dockerImage?: string;
  githubUrl?: string;
  savedInitialPrompt?: string;
  collapsed?: boolean;
  savedSelectedAgentIndex?: number;
  savedPromptedAgentIndexes?: number[];
  planFileName?: string;
  stepsEnabled?: boolean;
  // Coordinator fields
  coordinatorMode?: boolean;
  propagateSkipPermissions?: boolean;
  coordinatedBy?: string;
  controlledBy?: 'coordinator' | 'human';
  mcpConfigPath?: string;
  preambleFileExistedBefore?: boolean;
  signalDoneReceived?: boolean;
  signalDoneAt?: string;
  signalDoneConsumed?: boolean;
  needsReview?: boolean;
}

export interface PersistedTerminal {
  id: string;
  name: string;
}

export interface PersistedWindowState {
  x: number;
  y: number;
  width: number;
  height: number;
  maximized: boolean;
}

export type TelegramPushPolicy = 'all' | 'questions-only' | 'errors-only';
export type TelegramVoiceRuntime = 'none' | 'whisper-cpp' | 'openai';

export interface PersistedTelegramConfig {
  enabled: boolean;
  allowedChatIds: number[];
  pushPolicy: TelegramPushPolicy;
  redactPatterns: string[];
  extraQuestionPatterns: string[];
  publicBaseUrl: string | null;
  autoTunnel: boolean;
  cloudflaredPath: string | null;
  voice: {
    runtime: TelegramVoiceRuntime;
    whisperCppPath: string | null;
  };
}

export const DEFAULT_TELEGRAM_PERSISTED: PersistedTelegramConfig = {
  enabled: false,
  allowedChatIds: [],
  pushPolicy: 'questions-only',
  redactPatterns: [],
  extraQuestionPatterns: [],
  publicBaseUrl: null,
  autoTunnel: false,
  cloudflaredPath: null,
  voice: { runtime: 'none', whisperCppPath: null },
};

/** Current PersistedState schema version. Bumped to 2 when the telegram
 *  block was added; unversioned snapshots are treated as version 1. */
export const PERSISTENCE_VERSION = 2;

export interface PersistedState {
  /** Schema version. Missing/older treated as 1; written as PERSISTENCE_VERSION. */
  persistenceVersion?: number;
  projects: Project[];
  lastProjectId: string | null;
  lastAgentId: string | null;
  taskOrder: string[];
  collapsedTaskOrder?: string[];
  tasks: Record<string, PersistedTask>;
  terminals?: Record<string, PersistedTerminal>;
  activeTaskId: string | null;
  sidebarVisible: boolean;
  panelUserSize?: Record<string, number>;
  /** Marks that panelUserSize has been migrated past v1-style flex-weight
   *  values. Absent = pre-v2 data, wipe task:* entries on load. */
  panelUserSizeMigratedV2?: boolean;
  globalScale?: number;
  completedTaskDate?: string;
  completedTaskCount?: number;
  mergedLinesAdded?: number;
  mergedLinesRemoved?: number;
  terminalFont?: string;
  themePreset?: LookPreset;
  showPromptInput?: boolean;
  fontSmoothing?: boolean;
  windowState?: PersistedWindowState;
  autoTrustFolders?: boolean;
  showPlans?: boolean;
  showSteps?: boolean;
  showSidebarTips?: boolean;
  showSidebarProgress?: boolean;
  projectsCollapsed?: boolean;
  desktopNotificationsEnabled?: boolean;
  inactiveColumnOpacity?: number;
  editorCommand?: string;
  dockerImage?: string;
  shareDockerAgentAuth?: boolean;
  askCodeProvider?: 'claude' | 'minimax';
  customAgents?: AgentDef[];
  keybindingMigrationDismissed?: boolean;
  focusMode?: boolean;
  verboseLogging?: boolean;
  activeCustomThemeId?: string | null;
  appearanceMode?: AppearanceMode;
  lightThemePreset?: LookPreset;
  lightThemeCustomId?: string | null;
  darkThemePreset?: LookPreset;
  darkThemeCustomId?: string | null;
  /** Non-secret Telegram bot config. Bot token and OpenAI API key are NOT
   *  here — they live in the main process via Electron `safeStorage`. */
  telegram?: PersistedTelegramConfig;
  coordinatorModeEnabled?: boolean;
  coordinatorNotificationDelayMs?: number;
  coordinatorControlHintDismissed?: boolean;
}

export interface MCPStatus {
  running: boolean;
  port: number | null;
  coordinatorTaskId: string | null;
  mcpConfigPath: string | null;
}

// Panel cell IDs. Shell terminals use "shell:0", "shell:1", etc.
// Shell toolbar buttons use "shell-toolbar:0", "shell-toolbar:1", etc.
export type PanelId = string;

export interface PendingAction {
  type: 'close' | 'merge' | 'push';
  taskId: string;
}

export type PublicTunnelState = 'idle' | 'starting' | 'active' | 'error';

export interface RemoteAccess {
  enabled: boolean;
  token: string | null;
  port: number;
  url: string | null;
  wifiUrl: string | null;
  tailscaleUrl: string | null;
  connectedClients: number;
  publicUrl: string | null;
  publicTunnelState: PublicTunnelState;
  publicTunnelError: string | null;
}

export interface AppStore {
  projects: Project[];
  lastProjectId: string | null;
  lastAgentId: string | null;
  taskOrder: string[];
  collapsedTaskOrder: string[];
  tasks: Record<string, Task>;
  terminals: Record<string, Terminal>;
  agents: Record<string, Agent>;
  activeTaskId: string | null;
  activeAgentId: string | null;
  availableAgents: AgentDef[];
  customAgents: AgentDef[];
  showNewTaskDialog: boolean;
  sidebarVisible: boolean;
  /** User-dragged sizes keyed by `${persistKey}:${childId}`. Presence of an
   *  entry means that panel is pinned; absence means it's content-sized or
   *  flex-absorbing. */
  panelUserSize: Record<string, number>;
  globalScale: number;
  taskGitStatus: Record<string, TaskGitStatusSnapshot>;
  taskViewportVisibility: Record<string, TaskViewportVisibility>;
  focusedPanel: Record<string, PanelId>;
  sidebarFocused: boolean;
  sidebarFocusedProjectId: string | null;
  sidebarFocusedTaskId: string | null;
  placeholderFocused: boolean;
  placeholderFocusedButton: 'add-task' | 'add-terminal';
  showHelpDialog: boolean;
  showSettingsDialog: boolean;
  pendingAction: PendingAction | null;
  notification: string | null;
  completedTaskDate: string;
  completedTaskCount: number;
  mergedLinesAdded: number;
  mergedLinesRemoved: number;
  terminalFont: string;
  themePreset: LookPreset;
  showPromptInput: boolean;
  fontSmoothing: boolean;
  windowState: PersistedWindowState | null;
  autoTrustFolders: boolean;
  showPlans: boolean;
  showSteps: boolean;
  showSidebarTips: boolean;
  showSidebarProgress: boolean;
  projectsCollapsed: boolean;
  desktopNotificationsEnabled: boolean;
  inactiveColumnOpacity: number;
  editorCommand: string;
  dockerImage: string;
  dockerAvailable: boolean;
  shareDockerAgentAuth: boolean;
  askCodeProvider: 'claude' | 'minimax';
  newTaskDropUrl: string | null;
  newTaskPrefillPrompt: { prompt: string; projectId: string | null } | null;
  missingProjectIds: Record<string, true>;
  remoteAccess: RemoteAccess;
  showArena: boolean;
  keybindingPreset: string;
  /** Per-preset user overrides. Outer key = preset ID, inner = binding ID → override. */
  keybindingOverridesByPreset: Record<string, Record<string, KeybindingOverride>>;
  keybindingMigrationDismissed: boolean;
  focusMode: boolean;
  /** Per-task flag: true when the task is rendering its focus-mode two-column layout. */
  taskSplitMode: Record<string, boolean>;
  verboseLogging: boolean;
  customThemes: Record<string, CustomTheme>;
  activeCustomThemeId: string | null;
  appearanceMode: AppearanceMode;
  lightThemePreset: LookPreset;
  lightThemeCustomId: string | null;
  darkThemePreset: LookPreset;
  darkThemeCustomId: string | null;
  telegram: PersistedTelegramConfig;
  telegramHasToken: boolean;
  coordinatorModeEnabled: boolean;
  coordinatorNotificationDelayMs: number;
  coordinatorControlHintDismissed: boolean;
  mcpStatus: MCPStatus;
}
