import type { KeyBinding } from './types';

export const DEFAULT_BINDINGS: KeyBinding[] = [
  // -------------------------------------------------------------------------
  // App layer — Navigation
  // -------------------------------------------------------------------------
  {
    id: 'app.nav.row-up',
    layer: 'app',
    category: 'Navigation',
    description: 'Focus pane above',
    platform: 'both',
    key: 'ArrowUp',
    modifiers: { alt: true },
    action: 'navigateRow:up',
    global: true,
  },
  {
    id: 'app.nav.row-down',
    layer: 'app',
    category: 'Navigation',
    description: 'Focus pane below',
    platform: 'both',
    key: 'ArrowDown',
    modifiers: { alt: true },
    action: 'navigateRow:down',
    global: true,
  },
  {
    id: 'app.nav.column-left',
    layer: 'app',
    category: 'Navigation',
    description: 'Focus task left',
    platform: 'both',
    key: 'ArrowLeft',
    modifiers: { alt: true },
    action: 'navigateColumn:left',
    global: true,
  },
  {
    id: 'app.nav.column-right',
    layer: 'app',
    category: 'Navigation',
    description: 'Focus task right',
    platform: 'both',
    key: 'ArrowRight',
    modifiers: { alt: true },
    action: 'navigateColumn:right',
    global: true,
  },
  // Cmd+Opt+Arrow on macOS (Chrome-style tab switching). On Linux, Ctrl+Alt+Arrow
  // is captured by GNOME/KDE for workspace switching, so use Ctrl+PageUp/PageDown
  // instead — same shortcut Chrome and Firefox use for tabs on Linux.
  {
    id: 'app.nav.task-left',
    layer: 'app',
    category: 'Navigation',
    description: 'Switch to previous task',
    platform: 'mac',
    key: 'ArrowLeft',
    modifiers: { cmdOrCtrl: true, alt: true },
    action: 'navigateTask:left',
    global: true,
  },
  {
    id: 'app.nav.task-right',
    layer: 'app',
    category: 'Navigation',
    description: 'Switch to next task',
    platform: 'mac',
    key: 'ArrowRight',
    modifiers: { cmdOrCtrl: true, alt: true },
    action: 'navigateTask:right',
    global: true,
  },
  {
    id: 'app.nav.task-left-linux',
    layer: 'app',
    category: 'Navigation',
    description: 'Switch to previous task',
    platform: 'linux',
    key: 'PageUp',
    modifiers: { cmdOrCtrl: true },
    action: 'navigateTask:left',
    global: true,
  },
  {
    id: 'app.nav.task-right-linux',
    layer: 'app',
    category: 'Navigation',
    description: 'Switch to next task',
    platform: 'linux',
    key: 'PageDown',
    modifiers: { cmdOrCtrl: true },
    action: 'navigateTask:right',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — Task reordering
  // -------------------------------------------------------------------------
  // This binding is global, so it must not shadow native text selection in
  // inputs/terminals. Each platform uses the Shift+modifier+Arrow combo that
  // ISN'T a text selection there: on Linux, Ctrl+Shift+Arrow is select-by-word
  // (so use Alt+Shift+Arrow); on macOS, Cmd+Shift = select-to-line and
  // Opt+Shift = select-by-word, while Ctrl+Shift+Arrow is unbound (so use it).
  // Alt+Shift+Arrow is not a default GNOME/KDE global (unlike Ctrl+Alt+Arrow),
  // though a tiling WM could rebind it — acceptable given the constraints.
  {
    id: 'app.task.reorder-left',
    layer: 'app',
    category: 'Tasks',
    description: 'Move task left',
    platform: 'mac',
    key: 'ArrowLeft',
    modifiers: { ctrl: true, shift: true },
    action: 'moveActiveTask:left',
    global: true,
  },
  {
    id: 'app.task.reorder-right',
    layer: 'app',
    category: 'Tasks',
    description: 'Move task right',
    platform: 'mac',
    key: 'ArrowRight',
    modifiers: { ctrl: true, shift: true },
    action: 'moveActiveTask:right',
    global: true,
  },
  {
    id: 'app.task.reorder-left-linux',
    layer: 'app',
    category: 'Tasks',
    description: 'Move task left',
    platform: 'linux',
    key: 'ArrowLeft',
    modifiers: { alt: true, shift: true },
    action: 'moveActiveTask:left',
    global: true,
  },
  {
    id: 'app.task.reorder-right-linux',
    layer: 'app',
    category: 'Tasks',
    description: 'Move task right',
    platform: 'linux',
    key: 'ArrowRight',
    modifiers: { alt: true, shift: true },
    action: 'moveActiveTask:right',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — Jump to task by position (Cmd+1 through Cmd+9)
  // -------------------------------------------------------------------------
  // Shift variants for keyboard layouts where the digit row requires Shift
  // (e.g. AZERTY) live in shortcuts.ts (registerJumpToTaskShortcuts), mirroring
  // the Cmd+0 reset-zoom pattern — keeping them out of the registry avoids
  // duplicating these rows in the keybindings UI.
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `app.nav.jump-to-task-${i + 1}`,
    layer: 'app' as const,
    category: 'Navigation',
    description: `Jump to task ${i + 1}`,
    platform: 'both' as const,
    key: `${i + 1}`,
    modifiers: { cmdOrCtrl: true },
    action: `jumpToTask:${i + 1}`,
    global: true,
  })),

  // -------------------------------------------------------------------------
  // App layer — Task actions
  // -------------------------------------------------------------------------
  {
    id: 'app.task.close-shell',
    layer: 'app',
    category: 'Tasks',
    description: 'Close current shell',
    platform: 'both',
    key: 'w',
    modifiers: { cmdOrCtrl: true },
    action: 'closeShell',
    global: true,
  },
  {
    id: 'app.task.close',
    layer: 'app',
    category: 'Tasks',
    description: 'Close task',
    platform: 'both',
    key: 'W',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'closeTask',
    global: true,
  },
  {
    id: 'app.task.merge',
    layer: 'app',
    category: 'Tasks',
    description: 'Merge task',
    platform: 'both',
    key: 'M',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'mergeTask',
    global: true,
  },
  {
    id: 'app.task.push',
    layer: 'app',
    category: 'Tasks',
    description: 'Push task',
    platform: 'both',
    key: 'P',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'pushTask',
    global: true,
  },
  {
    id: 'app.task.new-shell',
    layer: 'app',
    category: 'Tasks',
    description: 'Spawn shell for task',
    platform: 'both',
    key: 'T',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'spawnShell',
    global: true,
  },
  {
    id: 'app.task.send-prompt',
    layer: 'app',
    category: 'Tasks',
    description: 'Send prompt',
    platform: 'both',
    key: 'Enter',
    modifiers: { cmdOrCtrl: true },
    action: 'sendPrompt',
    global: true,
  },

  // -------------------------------------------------------------------------
  // App layer — App shortcuts
  // -------------------------------------------------------------------------
  {
    id: 'app.new-terminal',
    layer: 'app',
    category: 'App',
    description: 'Create terminal',
    platform: 'both',
    key: 'D',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'createTerminal',
    global: true,
  },
  {
    id: 'app.new-task',
    layer: 'app',
    category: 'App',
    description: 'New task',
    platform: 'both',
    key: 'n',
    modifiers: { cmdOrCtrl: true },
    action: 'newTask',
    global: true,
  },
  {
    id: 'app.new-task-alt',
    layer: 'app',
    category: 'App',
    description: 'New task (alternate shortcut)',
    platform: 'both',
    key: 'a',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'newTask',
    global: true,
  },
  {
    id: 'app.toggle-sidebar',
    layer: 'app',
    category: 'App',
    description: 'Toggle sidebar',
    platform: 'both',
    key: 'b',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleSidebar',
    // NOT global — only fires outside input/terminal
  },
  {
    id: 'app.toggle-focus-mode',
    layer: 'app',
    category: 'App',
    description: 'Toggle focus mode / side-by-side view',
    platform: 'both',
    key: 'F',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'toggleFocusMode',
    global: true,
  },
  {
    id: 'app.toggle-help',
    layer: 'app',
    category: 'App',
    description: 'Toggle help dialog',
    platform: 'both',
    key: '/',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleHelp',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.toggle-help-f1',
    layer: 'app',
    category: 'App',
    description: 'Toggle help dialog (F1)',
    platform: 'both',
    key: 'F1',
    modifiers: {},
    action: 'toggleHelp',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.toggle-settings',
    layer: 'app',
    category: 'App',
    description: 'Toggle settings dialog',
    platform: 'both',
    key: ',',
    modifiers: { cmdOrCtrl: true },
    action: 'toggleSettings',
    global: true,
    dialogSafe: true,
  },
  {
    id: 'app.close-dialogs',
    layer: 'app',
    category: 'App',
    description: 'Close dialogs',
    platform: 'both',
    key: 'Escape',
    modifiers: {},
    action: 'closeDialogs',
    dialogSafe: true,
    // NOT global
  },
  {
    id: 'app.reset-zoom',
    layer: 'app',
    category: 'App',
    description: 'Reset zoom',
    platform: 'both',
    key: '0',
    modifiers: { cmdOrCtrl: true },
    action: 'resetZoom',
    global: true,
  },

  // -------------------------------------------------------------------------
  // Terminal layer — Copy / Paste
  // -------------------------------------------------------------------------
  {
    id: 'term.copy',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Copy selection',
    platform: 'mac',
    key: 'c',
    modifiers: { meta: true },
    action: 'copy',
  },
  {
    id: 'term.copy-linux',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Copy selection',
    platform: 'linux',
    key: 'C',
    modifiers: { ctrl: true, shift: true },
    action: 'copy',
  },
  {
    id: 'term.paste',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Paste clipboard',
    platform: 'mac',
    key: 'v',
    modifiers: { meta: true },
    action: 'paste',
  },
  {
    id: 'term.paste-linux',
    layer: 'terminal',
    category: 'Clipboard',
    description: 'Paste clipboard',
    platform: 'linux',
    key: 'V',
    modifiers: { ctrl: true, shift: true },
    action: 'paste',
  },

  // -------------------------------------------------------------------------
  // Terminal layer — Special keys
  // -------------------------------------------------------------------------
  {
    id: 'term.shift-enter',
    layer: 'terminal',
    category: 'Editing',
    description: 'Send newline (Shift+Enter)',
    platform: 'both',
    key: 'Enter',
    modifiers: { shift: true },
    escapeSequence: '\x1b\r',
  },
  {
    id: 'term.home',
    layer: 'terminal',
    category: 'Editing',
    description: 'Move to beginning of line',
    platform: 'mac',
    key: 'ArrowLeft',
    modifiers: { meta: true },
    escapeSequence: '\x1b[H',
  },
  {
    id: 'term.end',
    layer: 'terminal',
    category: 'Editing',
    description: 'Move to end of line',
    platform: 'mac',
    key: 'ArrowRight',
    modifiers: { meta: true },
    escapeSequence: '\x1b[F',
  },
  {
    id: 'term.kill-line',
    layer: 'terminal',
    category: 'Editing',
    description: 'Kill line backward',
    platform: 'mac',
    key: 'Backspace',
    modifiers: { meta: true },
    escapeSequence: '\x15',
  },

  // -------------------------------------------------------------------------
  // Terminal layer — Scrollback navigation
  // -------------------------------------------------------------------------
  {
    id: 'term.scroll-line-up',
    layer: 'terminal',
    category: 'Scrollback',
    description: 'Scroll up one line',
    platform: 'both',
    key: 'ArrowUp',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'scrollback:line-up',
  },
  {
    id: 'term.scroll-line-down',
    layer: 'terminal',
    category: 'Scrollback',
    description: 'Scroll down one line',
    platform: 'both',
    key: 'ArrowDown',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'scrollback:line-down',
  },
  {
    id: 'term.scroll-page-up',
    layer: 'terminal',
    category: 'Scrollback',
    description: 'Scroll up one page',
    platform: 'both',
    key: 'PageUp',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'scrollback:page-up',
  },
  {
    id: 'term.scroll-page-down',
    layer: 'terminal',
    category: 'Scrollback',
    description: 'Scroll down one page',
    platform: 'both',
    key: 'PageDown',
    modifiers: { cmdOrCtrl: true, shift: true },
    action: 'scrollback:page-down',
  },
];
